@BaseUrl=http://localhost:3000
@authToken=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsIm5hbWUiOiLmnY7lsI_nga8iLCJpYXQiOjE2MjE4Mjc3NjcsImV4cCI6MTYyMTgzMTM2N30.jbzZ7HdzU4X8aGOJV-wmgR43cpxoMrL8-2NZ8pp9o6c

### User FindMany
GET {{BaseUrl}}/apis/users?take=10&skip=0&name=月 HTTP/1.1
Authorization: {{authToken}}

### User FindOne
GET {{BaseUrl}}/apis/users/2 HTTP/1.1

### User Create
POST {{BaseUrl}}/apis/users HTTP/1.1
Content-Type: application/json

{
  "name": "尚波",
  "password": "aa123456",
  "email": "shangbo@gmail.com",
  "status": 1
}

### User Update
PATCH {{BaseUrl}}/apis/users/3 HTTP/1.1
Content-Type: application/json

{
  "password": "f123456"
}

### User Soft Delete
PATCH {{BaseUrl}}/apis/users/delete/10 HTTP/1.1

### User Delete
Delete {{BaseUrl}}/apis/users/11 HTTP/1.1

### User register
POST {{BaseUrl}}/apis/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "李小灯",
  "password": "dd254618"
}

### User login
POST {{BaseUrl}}/apis/auth/login HTTP/1.1
Content-Type: application/json

{
  "name": "李小灯",
  "password": "dd254618"
}

### User verify email send
POST {{BaseUrl}}/apis/mail/verify HTTP/1.1
Content-Type: application/json

{
  "email": "bijiasuo1177@163.com",
  "name": "泽高"
}

### User forget password
POST {{BaseUrl}}/apis/auth/forget-password HTTP/1.1
Content-Type: application/json

{
  "email": "bijiasuo1177@163.com",
  "name": "泽高",
  "code": "927309",
  "password": "pp123456"
}

### User FindMany Book

### User Create Book

### User Update Book

### User Delete Book

### User FindMany Tag

### User Create Tag

### User Update Tag

### User Delete Tag

### Mail Records Find Mnay
GET {{BaseUrl}}/apis/mail-records/ HTTP/1.1
